version: '3'

services:

  node:
    build: .
    volumes: 
      - ./:/app
    container_name: node-your-broker
    tty: true
    stdin_open: true
    command: /bin/sh
    restart: always
    environment:
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=root
      - DATABASE_USER=root
      - DATABASE_PORT=3306
      - DATABASE_NAME=your_broker
      - DATABASE_DIALECT=mysql
      - PORT=3001
      - JWT_SECRET=secretJWT
    ports:
      - 3001:3001

  db:
    image: mysql:8.0.21
    container_name: db-your-broker
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306

networks:
  default:
    name: your_broker_net