version: '3.8'

services:

  node:
    build: .
    volumes: 
      - ./:/app
    container_name: node-your-broker
    tty: true
    stdin_open: true
    command: /bin/sh
    restart: always
    environment:
      - PORT=3001
      - DATABASE_HOST=localhost
      - DATABASE_PASSWORD=root
      - DATABASE_USER=root
      - DATABASE_PORT=3307
      - DATABASE_NAME=your_broker
      - DATABASE_DIALECT=mysql
    ports:
      - 3001:3001

  mysql:
    image: mysql:5.7
    container_name: db-your-broker
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
